### ISSUE TITLE
Update astropy.coordinates.EarthLocation.of_site for Lowell Observatory sites

### ISSUE THREAD

**Issue by joellama** [astropy/astropy-data#96]
Currently the sites list lowell and DCT (Discovery Channel Telescope). The DCT got renamed to the Lowell Discovery Telescope (LDT) earlier this year, could we add a duplicate entry for this? 

The lowell site actually points to the Anderson Mesa site which should be renamed to NPOI, the main telescope on that site and Lowell should point to the campus on Mars Hill in Flagstaff (35.202875, -111.664781, 2195m) where we now have research telescopes. 

Is this possible?

**Comment by eteq** [comment]
The DCT change is easy I *think* - we can change the "canonical" name for the-telescope-formerly-known-as-DCT to "Lowell Discovery Telescope", but have "Discovery Channel Telescope" remain as an alias?

`lowell` is trickier in that it's *possible* that some users are depending on that being consistent with past codes. The main reason I have that worry is that it originally came from the IRAF database (which explains why it's so old...).  So here's an idea:

1. Make NPOI (or whatever that stands for - I think it's "Navy Precision Optical Interferometer"?) as the "main" name for what's currently `lowell`, and add any aliases you also think might make sense with that name.
2. have "lowell" be an *alias* for that entry
3. add "Lowell Mars Hill" and/or "Lowell Main", "Lowellobs" and/or similar for the Flagstaff location.
4. (this may require a code change in `astropy`) - have any request for just 'lowell' raise a deprecation warning that the name is now ambiguous and shouldn't be used in future code.

or alternatively we can just do as you suggest, which is just doing 1 and 3 and having "lowell" be an alias for 3.

I might be over-thinking this, though  - I don't actually *know* that anyone is using the NPOI "Lowell"... But since it's in large part likely to impact Lowell users, @joellama, I'm wiiling to just accept whichever you think is best.

**Comment by hamogu** [comment]
That's been done in #121.
